title: "Law Defense Documentation"
description: "Enterprise-grade legal defense documentation for Crown v Tia - Comprehensive case analysis with scientific evidence, legal precedent, and expert testimony"
author: "Tia Astor"
email: "tia@example.com"
baseurl: "/Law"
url: "https://tiation.github.io"

markdown: kramdown
highlighter: rouge
theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - "*.orig"
  - "*.pdf"
  - "*.jpeg"
  - "*.jpg"
  - "*.png"
  - "*.mp4"
  - "*.txt"
  - "Messages/"
  - "Photos/"
  - "Precedents/"
  - "Endorsements/"
  - "Public-Advocacy/"
  - "brief/"
  - "book_attachment_theory/"
  - "docs/"

github:
  repository_url: https://github.com/tiation/Law
  
seo:
  name: "Law Defense Documentation"
  description: "Enterprise-grade legal defense documentation repository"
  author: "Tia Astor"
  
navigation:
  - title: "GitHub Repository"
    url: "https://github.com/tiation/Law"
  - title: "Documentation"
    url: "https://github.com/tiation/Law/blob/main/README.md"
