title: "Law Defense Documentation"
description: "Comprehensive legal defense documentation for Crown v Tia"
author: "Tia Astor"
email: "tia@example.com"
baseurl: "/Law"
url: "https://tiation.github.io"

markdown: kramdown
highlighter: rouge
theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - "*.orig"
